# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do

  desc "Build"
  lane :build_appstore do
    if is_ci
      puts "Running on CI!"
  
      setup_ci(
          force: true
      )
    end
    match(type: "appstore", readonly: true)
    cocoapods

    build_app(
      workspace: ENV["WORKSPACE"],
      scheme: ENV["SCHEME"]
    )
  end

  desc "Upload to Test Flight"
  lane :upload_testflight do
    inc
    build_appstore

    # https://docs.fastlane.tools/actions/upload_to_testflight
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: ENV["APP_STORE_CONNECT_APPLE_ID"],
    )
  end

  lane :getTeamNames do
    require "spaceship"
    clientTunes = Spaceship::Tunes.login(ENV["APPLE_ID"], ENV["FASTLANE_PASSWORD"])
    client = Spaceship::Portal.login(ENV["APPLE_ID"], ENV["FASTLANE_PASSWORD"])

    UI.message "* Developer Portal Team ID:"
    strDevPortal = ""
    client.teams.each do |team|
      UI.message "#{team["name"]} (#{team["teamId"]})"
      strDevPortal << "#{team["name"]} (#{team["teamId"]})||"
    end

    UI.message "* App Store Connect Team ID:"
    strClientTunes = ""
    clientTunes.teams.each do |team|
      UI.message "#{team["contentProvider"]["name"]} (#{team["contentProvider"]["contentProviderId"]})"
      strClientTunes << "#{team["contentProvider"]["name"]} (#{team["contentProvider"]["contentProviderId"]})||"
    end
  end

  desc "Increment Build Number"
  lane :inc do
    increment_build_number({
      build_number: latest_testflight_build_number + 1,
    })
  end

  desc "Download keys"
  lane :download_keys do
    match(type: "development", readonly: true)
    match(type: "adhoc", readonly: true)
    match(type: "appstore", readonly: true)
  end

  desc "Create keys for new developers"
  lane :create_keys do
    match(type: "development", force_for_new_devices: true)
    match(type: "adhoc", force_for_new_devices: true)
    match(type: "appstore")
  end

end
