# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
      desc “Install pod dependencies”
      lane :install_pods do
         cocoapods(
             podfile: "./Podfile",
             use_bundle_exec: false)
end
      
      desc "Incrementing Build Number"
      lane :increment_build do
           current_build_number = latest_testflight_build_number(version: "1.0")
           increment_build_number(
           build_number: current_build_number + 1
           )
      end
      desc “Archive and Build IPA”
      lane :build_ipa do
       install_pods
       increment_build
          gym(
             workspace: "../UmSimplesDiario/UmSimplesDiario.xcworkspace",
             scheme: "UmSimplesDiario",
             output_directory: "../UmSimplesDiario/UmSimplesDiario/ipa",
             output_name: "UmSimplesDiario.ipa",
             export_method: “app-store”,
             include_bitcode: false,
             clean: true)
          pilot(ipa: "./UmSimplesDiario/UmSimplesDiario/ipa/UmSimplesDiario.ipa")
       end
end