name: Test coverage

on:
  workflow_dispatch:
  pull_request:
   branches: [ develop ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

     # Step to run automated tests
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        fastlane tests
  
